footprint: [[-0.27, -0.21], [-0.27, 0.21], [0.27, 0.21], [0.27, -0.21]]
footprint_padding: 0.01

transform_tolerance: 0.5
update_frequency: 1.0
publish_frequency: 1.0

global_frame: /map
robot_base_frame: /base_footprint
resolution: 0.05

static_map: true
track_unknown_space: true

plugins:
  - {name: static, type: "costmap_2d::MapLayer"}
  - {name: coverage, type: "costmap_2d::CoverageLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}

static:
  map_topic: /slam/map
  subscribe_to_updates: false
  unknown_cost_value: 51
  lethal_cost_threshold: 61

coverage:
  map_topic: /exploration/sensor_coverage/kinect_space
  subscribe_to_updates: false

inflation:
  inflation_radius: 0.25
