footprint:
  width: 0.48
  height: 0.36

map_origin: SLAM
occupied_cell_thres: 0.51
global_frame: /map
robot_base_frame: /base_footprint
max_height: 1.00
orientation_circle: 0.03

subscribed_topic_names:
  map2d: /slam/map
  map3d: /octomap_full

published_topic_names:
  fused_coverage: /exploration/sensor_coverage/fused

service_server_names:
  flush_coverage: /exploration/flush_coverage

frames_to_track: [kinect_rgb_frame, left_camera_frame, right_camera_frame]
# frames_to_track: [kinect_rgb_frame, left_camera_frame, right_camera_frame, rear_pi_camera_frame]

# kinect_rgb_frame
kinect_rgb_frame:
  produces_surface_coverage: false
  covering_unknown: false
  published_topic_names:
    space_coverage: kinect_space
    area_coverage: area_covered
    surface_coverage: kinect_surface
  binary:
    space_coverage: true
    surface_coverage: false
  surface_blur_factor: 3
  sensor_range: 1.0
  # sensor_hfov: 58
  sensor_hfov: 45
  sensor_vfov: 45
  exploration_state: true
  identification_state: true
  hold_state: true

left_camera_frame:
  produces_surface_coverage: false
  covering_unknown: false
  published_topic_names:
    space_coverage: left_camera_space
    area_coverage: left_camera_area_covered
    surface_coverage: left_camera_surface
  binary:
    space_coverage: true
    surface_coverage: false
  surface_blur_factor: 3
  sensor_range: 1.0
  sensor_hfov: 45
  sensor_vfov: 48
  exploration_state: true
  identification_state: true
  hold_state: true

right_camera_frame:
  produces_surface_coverage: false
  covering_unknown: false
  published_topic_names:
    space_coverage: right_camera_space
    area_coverage: right_camera_area_covered
    surface_coverage: right_camera_surface
  binary:
    space_coverage: true
    surface_coverage: false
  surface_blur_factor: 3
  sensor_range: 1.0
  sensor_hfov: 45
  sensor_vfov: 48
  exploration_state: true
  identification_state: true
  hold_state: true

# rear_pi_camera_frame:
#   produces_surface_coverage: false
#   covering_unknown: false
#   published_topic_names:
#     space_coverage: rear_camera_space
#     area_coverage: rear_camera_area_covered
#     surface_coverage: rear_camera_surface
#   binary:
#     space_coverage: true
#     surface_coverage: false
#   surface_blur_factor: 3
#   sensor_range: 1.0
#   sensor_hfov: 45
#   sensor_vfov: 41.41
#   exploration_state: true
#   identification_state: true
#   hold_state: true
