footprint:
  width: 0.48
  height: 0.36

map_origin: SLAM
occupied_cell_thres: 0.51
global_frame: /map
robot_base_frame: /base_footprint
max_height: 1.00
orientation_circle: 0.03

subscribed_topic_names:
  map2d: /slam/map
  map3d: /octomap_full

published_topic_names:
  fused_coverage: /exploration/sensor_coverage/fused

service_server_names:
  flush_coverage: /exploration/flush_coverage

frames_to_track: [kinect_rgb_frame, left_sonar_frame, right_sonar_frame]

# kinect_rgb_frame
kinect_rgb_frame:
  produces_surface_coverage: false
  covering_unknown: false
  published_topic_names:
    space_coverage: kinect_space
    area_coverage: area_covered
    surface_coverage: kinect_surface
  binary:
    space_coverage: true
    surface_coverage: false
  surface_blur_factor: 3
  sensor_range: 1.5
  # sensor_hfov: 58
  sensor_hfov: 45
  sensor_vfov: 45
  exploration_state: true
  identification_state: true
  hold_state: true

left_sonar_frame:
  produces_surface_coverage: false
  covering_unknown: true
  published_topic_names:
    space_coverage: left_sonar_space
    area_coverage: left_sonar_area_covered
    surface_coverage: left_sonar_surface
  binary:
    space_coverage: true
    surface_coverage: false
  surface_blur_factor: 3
  sensor_range: 0.2
  sensor_hfov: 35
  sensor_vfov: 30
  exploration_state: true
  identification_state: true
  hold_state: true

right_sonar_frame:
  produces_surface_coverage: false
  covering_unknown: true
  published_topic_names:
    space_coverage: right_sonar_space
    area_coverage: right_sonar_area_covered
    surface_coverage: right_sonar_surface
  binary:
    space_coverage: true
    surface_coverage: false
  surface_blur_factor: 3
  sensor_range: 0.2
  sensor_hfov: 35
  sensor_vfov: 30
  exploration_state: true
  identification_state: true
  hold_state: true
