frames_to_track: [kinect_rgb_frame]

subscribed_topic_names:
    space_coverage: kinect_space
    surface_coverage: kinect_surface

# kinect_rgb_frame
kinect_rgb_frame:

  surface_blur_factor: 3
    sensor_range: 2.0
    sensor_hfov: 58
    sensor_vfov: 45
    exploration_state: true
    identification_state: true
    hold_state: true
